[package]
name = "sni_forwarder_cargo"
version = "0.1.0"
authors = ["Louise Newberry <louise@geekylou.me.uk>"]
edition = "2018"

[dependencies]
byteorder = "1"
tokio = { version = "1", features = ["full"] }
yaml-rust = "0.4"